name: psagot-2020-cv
channels:
  - conda
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - jupyter
  - autopep8
  - pytorch=1.5.1
  - torchvision
  - cpuonly
  - opencv
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - pip
  - pip:
      - ipython-autotime
      - tqdm
